### ISSUE TITLE
Sync-Settings: Error updating backup

### ISSUE THREAD

**Issue by C00kie-** [UziTech/sync-settings-git-location#58]
Hello again, :D

So it looks like my twitter username doesn't fit the parser. Usually the "-" character makes some troubles.
Can we quick fix it or do I need to change my username? ;)

Thanks 

> Command failed: git clone --depth 1 http://github.com/C00kie-/atom-config.git .
Cloning into '.'...
fatal: could not read Username for 'https://github.com': No such device or address

**Comment by UziTech** [comment]
That looks like something that would have to fixed on Github not in this package.

After a quick google search I found this: https://github.com/github/hub/issues/1644

It looks like it may be an authentication issue. Github is essentially throwing a 404 since it is a private repo and your computer is not authenticated properly.

**Comment by C00kie-** [comment]
got it!
thks
